### ISSUE TITLE
Some duplication of signing functionality

### ISSUE THREAD

**Issue by cthulhu-rider** [nspcc-dev/neofs-sdk-go#155] opened 2022-02-25 09:47 UTC
`util/signature` package seems like a partial duplication of eponymous package in NeoFS API Go module. We need to anchor design: what stays there (signing of stable-marshalers only?) and what we support here in SDK. 

@fyrchik pls report ur thoughts about this.

**Comment by fyrchik** [comment] 2022-02-25 09:53
I think SDK can alter api-go functionality in 2 ways:
1. More convenient/extendable interface (use SDK types, use interfaces for signers) + SDK is simpler to refactor and update.
2. Adding new private signing schemes for custom installations, which are missing from `neofs-api` by design. This is where we could implement something like `sigutil.RegisterScheme(id, signer)`.

So, while there is a little duplication I don't like reusing api-go functionality directly. We may export specific helpers for checking signature for each scheme, though.

**Comment by cthulhu-rider** [comment] 2022-04-22 11:19
See also #219.

**Comment by cthulhu-rider** [comment] 2023-04-21 05:43
btw we don't have `util/signature` anymore, only `crypto`

**Comment by smallhive** [comment] 2023-04-27 06:14
Closing according to #219

**Closed by smallhive** 2023-04-27 06:14 UTC
